# Site settings
title: 标准酷
email: ruochen.xu@gmail.com
description: "京ICP备14040458号"
baseurl: ""
url: "http://cstdlib.com"
port: 8080
detach: TRUE

# Build settings
markdown: kramdown
permalink: pretty
